// Code generated by https://github.com/nicheinc/mock. DO NOT EDIT.

package directive

import (
	"fmt"
	"html/template"
	. "os"
	"sync/atomic"
	"testing"
	renamed "text/template"

	"github.com/nicheinc/mock/examples/directive/internal"
)

// ExampleMock is a mock implementation of the Example
// interface.
type ExampleMock struct {
	T                                        *testing.T
	NoParamsOrReturnStub                     func()
	NoParamsOrReturnCalled                   atomic.Int32
	UnnamedParamStub                         func(string)
	UnnamedParamCalled                       atomic.Int32
	UnnamedVariadicParamStub                 func(...string)
	UnnamedVariadicParamCalled               atomic.Int32
	BlankParamStub                           func(_ string)
	BlankParamCalled                         atomic.Int32
	BlankVariadicParamStub                   func(_ ...string)
	BlankVariadicParamCalled                 atomic.Int32
	NamedParamStub                           func(str string)
	NamedParamCalled                         atomic.Int32
	NamedVariadicParamStub                   func(strs ...string)
	NamedVariadicParamCalled                 atomic.Int32
	SameTypeNamedParamsStub                  func(str1 string, str2 string)
	SameTypeNamedParamsCalled                atomic.Int32
	InternalTypeParamStub                    func(internal internal.Internal)
	InternalTypeParamCalled                  atomic.Int32
	ImportedParamStub                        func(tmpl template.Template)
	ImportedParamCalled                      atomic.Int32
	ImportedVariadicParamStub                func(tmpl ...template.Template)
	ImportedVariadicParamCalled              atomic.Int32
	RenamedImportParamStub                   func(tmpl renamed.Template)
	RenamedImportParamCalled                 atomic.Int32
	RenamedImportVariadicParamStub           func(tmpls ...renamed.Template)
	RenamedImportVariadicParamCalled         atomic.Int32
	DotImportParamStub                       func(file File)
	DotImportParamCalled                     atomic.Int32
	DotImportVariadicParamStub               func(files ...File)
	DotImportVariadicParamCalled             atomic.Int32
	SelfReferentialParamStub                 func(intf Example)
	SelfReferentialParamCalled               atomic.Int32
	SelfReferentialVariadicParamStub         func(intf ...Example)
	SelfReferentialVariadicParamCalled       atomic.Int32
	StructParamStub                          func(obj struct{ num int })
	StructParamCalled                        atomic.Int32
	StructVariadicParamStub                  func(objs ...struct{ num int })
	StructVariadicParamCalled                atomic.Int32
	EmbeddedStructParamStub                  func(obj struct{ int })
	EmbeddedStructParamCalled                atomic.Int32
	EmbeddedStructVariadicParamStub          func(objs ...struct{ int })
	EmbeddedStructVariadicParamCalled        atomic.Int32
	EmptyInterfaceParamStub                  func(intf any)
	EmptyInterfaceParamCalled                atomic.Int32
	EmptyInterfaceVariadicParamStub          func(intf ...any)
	EmptyInterfaceVariadicParamCalled        atomic.Int32
	InterfaceParamStub                       func(intf interface{ MyFunc(num int) error })
	InterfaceParamCalled                     atomic.Int32
	InterfaceVariadicParamStub               func(intf ...interface{ MyFunc(num int) error })
	InterfaceVariadicParamCalled             atomic.Int32
	InterfaceVariadicFuncParamStub           func(intf interface{ MyFunc(nums ...int) error })
	InterfaceVariadicFuncParamCalled         atomic.Int32
	InterfaceVariadicFuncVariadicParamStub   func(intf ...interface{ MyFunc(nums ...int) error })
	InterfaceVariadicFuncVariadicParamCalled atomic.Int32
	EmbeddedInterfaceParamStub               func(intf interface{ fmt.Stringer })
	EmbeddedInterfaceParamCalled             atomic.Int32
	ChannelParamStub                         func(chanParam chan int)
	ChannelParamCalled                       atomic.Int32
	MapParamStub                             func(mapParam map[int]int)
	MapParamCalled                           atomic.Int32
	UnnamedReturnStub                        func() error
	UnnamedReturnCalled                      atomic.Int32
	MultipleUnnamedReturnStub                func() (int, error)
	MultipleUnnamedReturnCalled              atomic.Int32
	BlankReturnStub                          func() (_ error)
	BlankReturnCalled                        atomic.Int32
	NamedReturnStub                          func() (err error)
	NamedReturnCalled                        atomic.Int32
	SameTypeNamedReturnStub                  func() (err1 error, err2 error)
	SameTypeNamedReturnCalled                atomic.Int32
	RenamedImportReturnStub                  func() (tmpl renamed.Template)
	RenamedImportReturnCalled                atomic.Int32
	DotImportReturnStub                      func() (file File)
	DotImportReturnCalled                    atomic.Int32
	SelfReferentialReturnStub                func() (intf Example)
	SelfReferentialReturnCalled              atomic.Int32
	StructReturnStub                         func() (obj struct{ num int })
	StructReturnCalled                       atomic.Int32
	EmbeddedStructReturnStub                 func() (obj struct{ int })
	EmbeddedStructReturnCalled               atomic.Int32
	EmptyInterfaceReturnStub                 func() (intf any)
	EmptyInterfaceReturnCalled               atomic.Int32
	InterfaceReturnStub                      func() (intf interface{ MyFunc(num int) error })
	InterfaceReturnCalled                    atomic.Int32
	InterfaceVariadicFuncReturnStub          func() (intf interface{ MyFunc(nums ...int) error })
	InterfaceVariadicFuncReturnCalled        atomic.Int32
	EmbeddedInterfaceReturnStub              func() (intf interface{ fmt.Stringer })
	EmbeddedInterfaceReturnCalled            atomic.Int32
	ChannelReturnStub                        func() chan int
	ChannelReturnCalled                      atomic.Int32
	MapReturnStub                            func() map[int]int
	MapReturnCalled                          atomic.Int32
	SharedMethodStub                         func()
	SharedMethodCalled                       atomic.Int32
	MethodAStub                              func()
	MethodACalled                            atomic.Int32
	MethodBStub                              func()
	MethodBCalled                            atomic.Int32
}

// Verify that *ExampleMock implements Example.
var _ Example = &ExampleMock{}

// NoParamsOrReturn is a stub for the Example.NoParamsOrReturn
// method that records the number of times it has been called.
func (m *ExampleMock) NoParamsOrReturn() {
	m.NoParamsOrReturnCalled.Add(1)
	if m.NoParamsOrReturnStub == nil {
		if m.T != nil {
			m.T.Error("NoParamsOrReturnStub is nil")
		}
		panic("NoParamsOrReturn unimplemented")
	}
	m.NoParamsOrReturnStub()
}

// UnnamedParam is a stub for the Example.UnnamedParam
// method that records the number of times it has been called.
func (m *ExampleMock) UnnamedParam(param1 string) {
	m.UnnamedParamCalled.Add(1)
	if m.UnnamedParamStub == nil {
		if m.T != nil {
			m.T.Error("UnnamedParamStub is nil")
		}
		panic("UnnamedParam unimplemented")
	}
	m.UnnamedParamStub(param1)
}

// UnnamedVariadicParam is a stub for the Example.UnnamedVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) UnnamedVariadicParam(param1 ...string) {
	m.UnnamedVariadicParamCalled.Add(1)
	if m.UnnamedVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("UnnamedVariadicParamStub is nil")
		}
		panic("UnnamedVariadicParam unimplemented")
	}
	m.UnnamedVariadicParamStub(param1...)
}

// BlankParam is a stub for the Example.BlankParam
// method that records the number of times it has been called.
func (m *ExampleMock) BlankParam(param1 string) {
	m.BlankParamCalled.Add(1)
	if m.BlankParamStub == nil {
		if m.T != nil {
			m.T.Error("BlankParamStub is nil")
		}
		panic("BlankParam unimplemented")
	}
	m.BlankParamStub(param1)
}

// BlankVariadicParam is a stub for the Example.BlankVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) BlankVariadicParam(param1 ...string) {
	m.BlankVariadicParamCalled.Add(1)
	if m.BlankVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("BlankVariadicParamStub is nil")
		}
		panic("BlankVariadicParam unimplemented")
	}
	m.BlankVariadicParamStub(param1...)
}

// NamedParam is a stub for the Example.NamedParam
// method that records the number of times it has been called.
func (m *ExampleMock) NamedParam(str string) {
	m.NamedParamCalled.Add(1)
	if m.NamedParamStub == nil {
		if m.T != nil {
			m.T.Error("NamedParamStub is nil")
		}
		panic("NamedParam unimplemented")
	}
	m.NamedParamStub(str)
}

// NamedVariadicParam is a stub for the Example.NamedVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) NamedVariadicParam(strs ...string) {
	m.NamedVariadicParamCalled.Add(1)
	if m.NamedVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("NamedVariadicParamStub is nil")
		}
		panic("NamedVariadicParam unimplemented")
	}
	m.NamedVariadicParamStub(strs...)
}

// SameTypeNamedParams is a stub for the Example.SameTypeNamedParams
// method that records the number of times it has been called.
func (m *ExampleMock) SameTypeNamedParams(str1 string, str2 string) {
	m.SameTypeNamedParamsCalled.Add(1)
	if m.SameTypeNamedParamsStub == nil {
		if m.T != nil {
			m.T.Error("SameTypeNamedParamsStub is nil")
		}
		panic("SameTypeNamedParams unimplemented")
	}
	m.SameTypeNamedParamsStub(str1, str2)
}

// InternalTypeParam is a stub for the Example.InternalTypeParam
// method that records the number of times it has been called.
func (m *ExampleMock) InternalTypeParam(internal internal.Internal) {
	m.InternalTypeParamCalled.Add(1)
	if m.InternalTypeParamStub == nil {
		if m.T != nil {
			m.T.Error("InternalTypeParamStub is nil")
		}
		panic("InternalTypeParam unimplemented")
	}
	m.InternalTypeParamStub(internal)
}

// ImportedParam is a stub for the Example.ImportedParam
// method that records the number of times it has been called.
func (m *ExampleMock) ImportedParam(tmpl template.Template) {
	m.ImportedParamCalled.Add(1)
	if m.ImportedParamStub == nil {
		if m.T != nil {
			m.T.Error("ImportedParamStub is nil")
		}
		panic("ImportedParam unimplemented")
	}
	m.ImportedParamStub(tmpl)
}

// ImportedVariadicParam is a stub for the Example.ImportedVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) ImportedVariadicParam(tmpl ...template.Template) {
	m.ImportedVariadicParamCalled.Add(1)
	if m.ImportedVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("ImportedVariadicParamStub is nil")
		}
		panic("ImportedVariadicParam unimplemented")
	}
	m.ImportedVariadicParamStub(tmpl...)
}

// RenamedImportParam is a stub for the Example.RenamedImportParam
// method that records the number of times it has been called.
func (m *ExampleMock) RenamedImportParam(tmpl renamed.Template) {
	m.RenamedImportParamCalled.Add(1)
	if m.RenamedImportParamStub == nil {
		if m.T != nil {
			m.T.Error("RenamedImportParamStub is nil")
		}
		panic("RenamedImportParam unimplemented")
	}
	m.RenamedImportParamStub(tmpl)
}

// RenamedImportVariadicParam is a stub for the Example.RenamedImportVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) RenamedImportVariadicParam(tmpls ...renamed.Template) {
	m.RenamedImportVariadicParamCalled.Add(1)
	if m.RenamedImportVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("RenamedImportVariadicParamStub is nil")
		}
		panic("RenamedImportVariadicParam unimplemented")
	}
	m.RenamedImportVariadicParamStub(tmpls...)
}

// DotImportParam is a stub for the Example.DotImportParam
// method that records the number of times it has been called.
func (m *ExampleMock) DotImportParam(file File) {
	m.DotImportParamCalled.Add(1)
	if m.DotImportParamStub == nil {
		if m.T != nil {
			m.T.Error("DotImportParamStub is nil")
		}
		panic("DotImportParam unimplemented")
	}
	m.DotImportParamStub(file)
}

// DotImportVariadicParam is a stub for the Example.DotImportVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) DotImportVariadicParam(files ...File) {
	m.DotImportVariadicParamCalled.Add(1)
	if m.DotImportVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("DotImportVariadicParamStub is nil")
		}
		panic("DotImportVariadicParam unimplemented")
	}
	m.DotImportVariadicParamStub(files...)
}

// SelfReferentialParam is a stub for the Example.SelfReferentialParam
// method that records the number of times it has been called.
func (m *ExampleMock) SelfReferentialParam(intf Example) {
	m.SelfReferentialParamCalled.Add(1)
	if m.SelfReferentialParamStub == nil {
		if m.T != nil {
			m.T.Error("SelfReferentialParamStub is nil")
		}
		panic("SelfReferentialParam unimplemented")
	}
	m.SelfReferentialParamStub(intf)
}

// SelfReferentialVariadicParam is a stub for the Example.SelfReferentialVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) SelfReferentialVariadicParam(intf ...Example) {
	m.SelfReferentialVariadicParamCalled.Add(1)
	if m.SelfReferentialVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("SelfReferentialVariadicParamStub is nil")
		}
		panic("SelfReferentialVariadicParam unimplemented")
	}
	m.SelfReferentialVariadicParamStub(intf...)
}

// StructParam is a stub for the Example.StructParam
// method that records the number of times it has been called.
func (m *ExampleMock) StructParam(obj struct{ num int }) {
	m.StructParamCalled.Add(1)
	if m.StructParamStub == nil {
		if m.T != nil {
			m.T.Error("StructParamStub is nil")
		}
		panic("StructParam unimplemented")
	}
	m.StructParamStub(obj)
}

// StructVariadicParam is a stub for the Example.StructVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) StructVariadicParam(objs ...struct{ num int }) {
	m.StructVariadicParamCalled.Add(1)
	if m.StructVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("StructVariadicParamStub is nil")
		}
		panic("StructVariadicParam unimplemented")
	}
	m.StructVariadicParamStub(objs...)
}

// EmbeddedStructParam is a stub for the Example.EmbeddedStructParam
// method that records the number of times it has been called.
func (m *ExampleMock) EmbeddedStructParam(obj struct{ int }) {
	m.EmbeddedStructParamCalled.Add(1)
	if m.EmbeddedStructParamStub == nil {
		if m.T != nil {
			m.T.Error("EmbeddedStructParamStub is nil")
		}
		panic("EmbeddedStructParam unimplemented")
	}
	m.EmbeddedStructParamStub(obj)
}

// EmbeddedStructVariadicParam is a stub for the Example.EmbeddedStructVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) EmbeddedStructVariadicParam(objs ...struct{ int }) {
	m.EmbeddedStructVariadicParamCalled.Add(1)
	if m.EmbeddedStructVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("EmbeddedStructVariadicParamStub is nil")
		}
		panic("EmbeddedStructVariadicParam unimplemented")
	}
	m.EmbeddedStructVariadicParamStub(objs...)
}

// EmptyInterfaceParam is a stub for the Example.EmptyInterfaceParam
// method that records the number of times it has been called.
func (m *ExampleMock) EmptyInterfaceParam(intf any) {
	m.EmptyInterfaceParamCalled.Add(1)
	if m.EmptyInterfaceParamStub == nil {
		if m.T != nil {
			m.T.Error("EmptyInterfaceParamStub is nil")
		}
		panic("EmptyInterfaceParam unimplemented")
	}
	m.EmptyInterfaceParamStub(intf)
}

// EmptyInterfaceVariadicParam is a stub for the Example.EmptyInterfaceVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) EmptyInterfaceVariadicParam(intf ...any) {
	m.EmptyInterfaceVariadicParamCalled.Add(1)
	if m.EmptyInterfaceVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("EmptyInterfaceVariadicParamStub is nil")
		}
		panic("EmptyInterfaceVariadicParam unimplemented")
	}
	m.EmptyInterfaceVariadicParamStub(intf...)
}

// InterfaceParam is a stub for the Example.InterfaceParam
// method that records the number of times it has been called.
func (m *ExampleMock) InterfaceParam(intf interface{ MyFunc(num int) error }) {
	m.InterfaceParamCalled.Add(1)
	if m.InterfaceParamStub == nil {
		if m.T != nil {
			m.T.Error("InterfaceParamStub is nil")
		}
		panic("InterfaceParam unimplemented")
	}
	m.InterfaceParamStub(intf)
}

// InterfaceVariadicParam is a stub for the Example.InterfaceVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) InterfaceVariadicParam(intf ...interface{ MyFunc(num int) error }) {
	m.InterfaceVariadicParamCalled.Add(1)
	if m.InterfaceVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("InterfaceVariadicParamStub is nil")
		}
		panic("InterfaceVariadicParam unimplemented")
	}
	m.InterfaceVariadicParamStub(intf...)
}

// InterfaceVariadicFuncParam is a stub for the Example.InterfaceVariadicFuncParam
// method that records the number of times it has been called.
func (m *ExampleMock) InterfaceVariadicFuncParam(intf interface{ MyFunc(nums ...int) error }) {
	m.InterfaceVariadicFuncParamCalled.Add(1)
	if m.InterfaceVariadicFuncParamStub == nil {
		if m.T != nil {
			m.T.Error("InterfaceVariadicFuncParamStub is nil")
		}
		panic("InterfaceVariadicFuncParam unimplemented")
	}
	m.InterfaceVariadicFuncParamStub(intf)
}

// InterfaceVariadicFuncVariadicParam is a stub for the Example.InterfaceVariadicFuncVariadicParam
// method that records the number of times it has been called.
func (m *ExampleMock) InterfaceVariadicFuncVariadicParam(intf ...interface{ MyFunc(nums ...int) error }) {
	m.InterfaceVariadicFuncVariadicParamCalled.Add(1)
	if m.InterfaceVariadicFuncVariadicParamStub == nil {
		if m.T != nil {
			m.T.Error("InterfaceVariadicFuncVariadicParamStub is nil")
		}
		panic("InterfaceVariadicFuncVariadicParam unimplemented")
	}
	m.InterfaceVariadicFuncVariadicParamStub(intf...)
}

// EmbeddedInterfaceParam is a stub for the Example.EmbeddedInterfaceParam
// method that records the number of times it has been called.
func (m *ExampleMock) EmbeddedInterfaceParam(intf interface{ fmt.Stringer }) {
	m.EmbeddedInterfaceParamCalled.Add(1)
	if m.EmbeddedInterfaceParamStub == nil {
		if m.T != nil {
			m.T.Error("EmbeddedInterfaceParamStub is nil")
		}
		panic("EmbeddedInterfaceParam unimplemented")
	}
	m.EmbeddedInterfaceParamStub(intf)
}

// ChannelParam is a stub for the Example.ChannelParam
// method that records the number of times it has been called.
func (m *ExampleMock) ChannelParam(chanParam chan int) {
	m.ChannelParamCalled.Add(1)
	if m.ChannelParamStub == nil {
		if m.T != nil {
			m.T.Error("ChannelParamStub is nil")
		}
		panic("ChannelParam unimplemented")
	}
	m.ChannelParamStub(chanParam)
}

// MapParam is a stub for the Example.MapParam
// method that records the number of times it has been called.
func (m *ExampleMock) MapParam(mapParam map[int]int) {
	m.MapParamCalled.Add(1)
	if m.MapParamStub == nil {
		if m.T != nil {
			m.T.Error("MapParamStub is nil")
		}
		panic("MapParam unimplemented")
	}
	m.MapParamStub(mapParam)
}

// UnnamedReturn is a stub for the Example.UnnamedReturn
// method that records the number of times it has been called.
func (m *ExampleMock) UnnamedReturn() error {
	m.UnnamedReturnCalled.Add(1)
	if m.UnnamedReturnStub == nil {
		if m.T != nil {
			m.T.Error("UnnamedReturnStub is nil")
		}
		panic("UnnamedReturn unimplemented")
	}
	return m.UnnamedReturnStub()
}

// MultipleUnnamedReturn is a stub for the Example.MultipleUnnamedReturn
// method that records the number of times it has been called.
func (m *ExampleMock) MultipleUnnamedReturn() (int, error) {
	m.MultipleUnnamedReturnCalled.Add(1)
	if m.MultipleUnnamedReturnStub == nil {
		if m.T != nil {
			m.T.Error("MultipleUnnamedReturnStub is nil")
		}
		panic("MultipleUnnamedReturn unimplemented")
	}
	return m.MultipleUnnamedReturnStub()
}

// BlankReturn is a stub for the Example.BlankReturn
// method that records the number of times it has been called.
func (m *ExampleMock) BlankReturn() (_ error) {
	m.BlankReturnCalled.Add(1)
	if m.BlankReturnStub == nil {
		if m.T != nil {
			m.T.Error("BlankReturnStub is nil")
		}
		panic("BlankReturn unimplemented")
	}
	return m.BlankReturnStub()
}

// NamedReturn is a stub for the Example.NamedReturn
// method that records the number of times it has been called.
func (m *ExampleMock) NamedReturn() (err error) {
	m.NamedReturnCalled.Add(1)
	if m.NamedReturnStub == nil {
		if m.T != nil {
			m.T.Error("NamedReturnStub is nil")
		}
		panic("NamedReturn unimplemented")
	}
	return m.NamedReturnStub()
}

// SameTypeNamedReturn is a stub for the Example.SameTypeNamedReturn
// method that records the number of times it has been called.
func (m *ExampleMock) SameTypeNamedReturn() (err1 error, err2 error) {
	m.SameTypeNamedReturnCalled.Add(1)
	if m.SameTypeNamedReturnStub == nil {
		if m.T != nil {
			m.T.Error("SameTypeNamedReturnStub is nil")
		}
		panic("SameTypeNamedReturn unimplemented")
	}
	return m.SameTypeNamedReturnStub()
}

// RenamedImportReturn is a stub for the Example.RenamedImportReturn
// method that records the number of times it has been called.
func (m *ExampleMock) RenamedImportReturn() (tmpl renamed.Template) {
	m.RenamedImportReturnCalled.Add(1)
	if m.RenamedImportReturnStub == nil {
		if m.T != nil {
			m.T.Error("RenamedImportReturnStub is nil")
		}
		panic("RenamedImportReturn unimplemented")
	}
	return m.RenamedImportReturnStub()
}

// DotImportReturn is a stub for the Example.DotImportReturn
// method that records the number of times it has been called.
func (m *ExampleMock) DotImportReturn() (file File) {
	m.DotImportReturnCalled.Add(1)
	if m.DotImportReturnStub == nil {
		if m.T != nil {
			m.T.Error("DotImportReturnStub is nil")
		}
		panic("DotImportReturn unimplemented")
	}
	return m.DotImportReturnStub()
}

// SelfReferentialReturn is a stub for the Example.SelfReferentialReturn
// method that records the number of times it has been called.
func (m *ExampleMock) SelfReferentialReturn() (intf Example) {
	m.SelfReferentialReturnCalled.Add(1)
	if m.SelfReferentialReturnStub == nil {
		if m.T != nil {
			m.T.Error("SelfReferentialReturnStub is nil")
		}
		panic("SelfReferentialReturn unimplemented")
	}
	return m.SelfReferentialReturnStub()
}

// StructReturn is a stub for the Example.StructReturn
// method that records the number of times it has been called.
func (m *ExampleMock) StructReturn() (obj struct{ num int }) {
	m.StructReturnCalled.Add(1)
	if m.StructReturnStub == nil {
		if m.T != nil {
			m.T.Error("StructReturnStub is nil")
		}
		panic("StructReturn unimplemented")
	}
	return m.StructReturnStub()
}

// EmbeddedStructReturn is a stub for the Example.EmbeddedStructReturn
// method that records the number of times it has been called.
func (m *ExampleMock) EmbeddedStructReturn() (obj struct{ int }) {
	m.EmbeddedStructReturnCalled.Add(1)
	if m.EmbeddedStructReturnStub == nil {
		if m.T != nil {
			m.T.Error("EmbeddedStructReturnStub is nil")
		}
		panic("EmbeddedStructReturn unimplemented")
	}
	return m.EmbeddedStructReturnStub()
}

// EmptyInterfaceReturn is a stub for the Example.EmptyInterfaceReturn
// method that records the number of times it has been called.
func (m *ExampleMock) EmptyInterfaceReturn() (intf any) {
	m.EmptyInterfaceReturnCalled.Add(1)
	if m.EmptyInterfaceReturnStub == nil {
		if m.T != nil {
			m.T.Error("EmptyInterfaceReturnStub is nil")
		}
		panic("EmptyInterfaceReturn unimplemented")
	}
	return m.EmptyInterfaceReturnStub()
}

// InterfaceReturn is a stub for the Example.InterfaceReturn
// method that records the number of times it has been called.
func (m *ExampleMock) InterfaceReturn() (intf interface{ MyFunc(num int) error }) {
	m.InterfaceReturnCalled.Add(1)
	if m.InterfaceReturnStub == nil {
		if m.T != nil {
			m.T.Error("InterfaceReturnStub is nil")
		}
		panic("InterfaceReturn unimplemented")
	}
	return m.InterfaceReturnStub()
}

// InterfaceVariadicFuncReturn is a stub for the Example.InterfaceVariadicFuncReturn
// method that records the number of times it has been called.
func (m *ExampleMock) InterfaceVariadicFuncReturn() (intf interface{ MyFunc(nums ...int) error }) {
	m.InterfaceVariadicFuncReturnCalled.Add(1)
	if m.InterfaceVariadicFuncReturnStub == nil {
		if m.T != nil {
			m.T.Error("InterfaceVariadicFuncReturnStub is nil")
		}
		panic("InterfaceVariadicFuncReturn unimplemented")
	}
	return m.InterfaceVariadicFuncReturnStub()
}

// EmbeddedInterfaceReturn is a stub for the Example.EmbeddedInterfaceReturn
// method that records the number of times it has been called.
func (m *ExampleMock) EmbeddedInterfaceReturn() (intf interface{ fmt.Stringer }) {
	m.EmbeddedInterfaceReturnCalled.Add(1)
	if m.EmbeddedInterfaceReturnStub == nil {
		if m.T != nil {
			m.T.Error("EmbeddedInterfaceReturnStub is nil")
		}
		panic("EmbeddedInterfaceReturn unimplemented")
	}
	return m.EmbeddedInterfaceReturnStub()
}

// ChannelReturn is a stub for the Example.ChannelReturn
// method that records the number of times it has been called.
func (m *ExampleMock) ChannelReturn() chan int {
	m.ChannelReturnCalled.Add(1)
	if m.ChannelReturnStub == nil {
		if m.T != nil {
			m.T.Error("ChannelReturnStub is nil")
		}
		panic("ChannelReturn unimplemented")
	}
	return m.ChannelReturnStub()
}

// MapReturn is a stub for the Example.MapReturn
// method that records the number of times it has been called.
func (m *ExampleMock) MapReturn() map[int]int {
	m.MapReturnCalled.Add(1)
	if m.MapReturnStub == nil {
		if m.T != nil {
			m.T.Error("MapReturnStub is nil")
		}
		panic("MapReturn unimplemented")
	}
	return m.MapReturnStub()
}

// SharedMethod is a stub for the Example.SharedMethod
// method that records the number of times it has been called.
func (m *ExampleMock) SharedMethod() {
	m.SharedMethodCalled.Add(1)
	if m.SharedMethodStub == nil {
		if m.T != nil {
			m.T.Error("SharedMethodStub is nil")
		}
		panic("SharedMethod unimplemented")
	}
	m.SharedMethodStub()
}

// MethodA is a stub for the Example.MethodA
// method that records the number of times it has been called.
func (m *ExampleMock) MethodA() {
	m.MethodACalled.Add(1)
	if m.MethodAStub == nil {
		if m.T != nil {
			m.T.Error("MethodAStub is nil")
		}
		panic("MethodA unimplemented")
	}
	m.MethodAStub()
}

// MethodB is a stub for the Example.MethodB
// method that records the number of times it has been called.
func (m *ExampleMock) MethodB() {
	m.MethodBCalled.Add(1)
	if m.MethodBStub == nil {
		if m.T != nil {
			m.T.Error("MethodBStub is nil")
		}
		panic("MethodB unimplemented")
	}
	m.MethodBStub()
}
